# FROM node:lts-alpine3.23
# COPY . .
# RUN npm install
# EXPOSE 5000
# CMD [ "node", "index.js" ]

FROM node:lts-alpine3.23
RUN npm install -g nodemon
WORKDIR /app
COPY . .
RUN npm install
EXPOSE 5000
CMD [ "npm", "run", "dev" ]







# Command for build this docker file
# docker build -t basic-app .     (.) for current directory